// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3L_KCHm96PzEpAos5L5fteqwiKZyW6IQ',
    appId: '1:1010019863680:web:477a155866b29de6ec2a65',
    messagingSenderId: '1010019863680',
    projectId: 'bingo-75d49',
    authDomain: 'bingo-75d49.firebaseapp.com',
    databaseURL: 'https://bingo-75d49-default-rtdb.firebaseio.com',
    storageBucket: 'bingo-75d49.appspot.com',
    measurementId: 'G-NRCC8BE1YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFXAL1MC7kMFWfGRZgnQHbHIMSyoz3mEM',
    appId: '1:1010019863680:android:60f1eb92eaf4980aec2a65',
    messagingSenderId: '1010019863680',
    projectId: 'bingo-75d49',
    databaseURL: 'https://bingo-75d49-default-rtdb.firebaseio.com',
    storageBucket: 'bingo-75d49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwpdJ1eJ-DP8w_OuS29uVpDriORo8dQ_s',
    appId: '1:1010019863680:ios:2177271efc2174d4ec2a65',
    messagingSenderId: '1010019863680',
    projectId: 'bingo-75d49',
    databaseURL: 'https://bingo-75d49-default-rtdb.firebaseio.com',
    storageBucket: 'bingo-75d49.appspot.com',
    iosBundleId: 'com.thecwadley.bingo2',
  );

}